const mapping = {
  house: 'fa-solid fa-house-chimney',
  addressBook: 'fa-regular fa-address-book',
  airplane: 'fa-solid fa-plane',
  airplaneTakeoff: 'fa-solid fa-plane-departure',
  airplaneLanding: 'fa-solid fa-plane-arrival',
  anchor: 'fa-solid fa-anchor',
  archive: 'fa-solid fa-box-archive',
  arrowDown: 'fa-solid fa-arrow-down',
  arrowUp: 'fa-solid fa-arrow-up',
  arrowStart: 'fa-solid fa-arrow-left',
  arrowEnd: 'fa-solid fa-arrow-right',
  arrowCircleDown: 'fa-solid fa-circle-down',
  arrowCircleUp: 'fa-solid fa-circle-up',
  arrowCircleStart: 'fa-solid fa-circle-left',
  arrowCircleEnd: 'fa-solid fa-circle-right',
  arrowSquareDown: 'fa-solid fa-square-caret-down',
  arrowSquareUp: 'fa-solid fa-square-caret-up',
  arrowSquareStart: 'fa-solid fa-square-caret-left',
  arrowSquareEnd: 'fa-solid fa-square-caret-right',
  arrowFatDown: 'fa-solid fa-down-long',
  arrowFatUp: 'fa-solid fa-up-long',
  arrowFatStart: 'fa-solid fa-left-long',
  arrowFatEnd: 'fa-solid fa-right-long',
  arrowClockwise: 'fa-solid fa-arrow-rotate-right',
  arrowCounterClockwise: 'fa-solid fa-arrow-rotate-left',
  arrowsIn: 'fa-solid fa-minimize',
  arrowsOut: 'fa-solid fa-maximize',
  arrowsShuffle: 'fa-solid fa-shuffle',
  article: 'fa-regular fa-newspaper',
  asterisk: 'fa-solid fa-asterisk',
  at: 'fa-solid fa-at',
  atom: 'fa-solid fa-atom',
  baby: 'fa-solid fa-baby',
  bag: 'fa-solid fa-bag-shopping',
  bank: 'fa-solid fa-building-columns',
  barcode: 'fa-solid fa-barcode',
  barricade: 'fa-solid fa-road-barrier',
  baseball: 'fa-solid fa-baseball',
  basket: 'fa-solid fa-basket-shopping',
  basketball: 'fa-solid fa-basketball',
  batteryEmpty: 'fa-solid fa-battery-empty',
  batteryFull: 'fa-solid fa-battery-full',
  batteryHigh: 'fa-solid fa-battery-three-quarters',
  batteryLow: 'fa-solid fa-battery-quarter',
  bed: 'fa-solid fa-bed',
  beer: 'fa-solid fa-beer-mug-empty',
  bell: 'fa-solid fa-bell',
  bellSlash: 'fa-solid fa-bell-slash',
  bicycle: 'fa-solid fa-bicycle',
  binoculars: 'fa-solid fa-binoculars',
  bird: 'fa-solid fa-dove',
  boat: 'fa-solid fa-ship',
  bomb: 'fa-solid fa-bomb',
  book: 'fa-solid fa-book',
  bookOpen: 'fa-solid fa-book-open',
  bookmark: 'fa-regular fa-bookmark',
  bowl: 'fa-solid fa-bowl-food',
  bread: 'fa-solid fa-bread-slice',
  bridge: 'fa-solid fa-bridge',
  briefcase: 'fa-solid fa-briefcase',
  broadcast: 'fa-solid fa-tower-broadcast',
  broom: 'fa-solid fa-broom',
  bug: 'fa-solid fa-bug',
  building: 'fa-solid fa-building'
}

function iconset (ctx) {
  return {
    name: 'fontawesome',
    css: [
      'waibuFontawesome.virtual:/fa-free/css/fontawesome.min.css',
      'waibuFontawesome.virtual:/fa-free/css/regular.min.css',
      'waibuFontawesome.virtual:/fa-free/css/brands.min.css',
      'waibuFontawesome.virtual:/fa-free/css/solid.min.css'
    ],
    mapping
  }
}

export default iconset
